second_django/myblog/blog/urls.py
from django.urls import path,re_path
from . import views
app_name = 'blog'
urlpatterns = [
    path('index/', views.index),
    re_path('article/(?P<article_id>[0-9]+)/', views.article_page,name='article_page'),
    re_path('edit/(?P<article_id>[0-9]+)/',views.edit_page,name='edit_page'),
    path('edit/action/',views.edit_action,name='edit_action'),
]

second_django/myblog/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=32,default='title')
    content=models.TextField(null=True)
    # pub_time=models.DateTimeField(auto_now=True)
    pub_time=models.DateTimeField(null=True)
    def __str__(self):
        return self.title

second_django/myblog/blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from .import models
from django.contrib import messages

# Create your views here.




# def index(request):
#     return HttpResponse('hello,world!')
# 三个参数
# 第一个是request
# 第二个是网页模板
# 第三个是传给模板中的字典,在模板中使用{{ 字典的键 }}来引用,字典的值
# def index(request):
#     return render(request,'blog/index.html',{'hello':'hello blog\n从views传过来的字典'})
# def index(request):
#     article=models.Article.objects.get(pk=1)
    
#     return render(request,'blog/index.html',{'article':article})
def index(request):
    # 数据库的表的名字->Article
    #把所有数据存到articles中
    articles=models.Article.objects.all()
    print(request)
    return render(request,'blog/index.html',{'articles':articles})

def article_page(request,article_id):
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})
    # return HttpResponse('hello 我是views中的article_page函数')

def edit_page(request,article_id):
    print('到达edit_page函数')
    if str(article_id)==str(0):
        print('get edit_page view')
        return render(request,'blog/edit_page.html')
    article=models.Article.objects.get(pk=article_id)
    print(request)
    print(article)

    return render(request,'blog/edit_page.html',{'article':article})


def edit_action(request):
    title=request.POST.get('title','TITLE')
    print('title='+title)
    content=request.POST.get('content','CONTENT')
    print('content='+content)
    article_id=request.POST.get('article_id','0')
    print('article_id='+article_id)
    if article_id=='0':
        models.Article.objects.create(title=title,content=content)
        articles=models.Article.objects.all()
        return render(request,'blog/index.html',{'articles':articles})
    article=models.Article.objects.get(pk=article_id)
    article.title=title
    article.content=content
    article.save()
    return render(request,'blog/article_page.html',{'article':article})
    

second_django/myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article Page</title>
</head>
<body>
    <h1>{{article.content}}</h1>
    <br/><br/>
    <a href="{%url 'blog:edit_page' article.id%}">修改文章</a>

</body>
</html>

second_django/myblog/blog/templates/blog/edit_page.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit_Page</title>
</head>

<body>
    <form action="{%url 'blog:edit_action'%}" method='post'>
        {%csrf_token%}

        <input type='hidden' name="article_id" value="{{article.id | default:'0'}}" />
        <label for="">文章标题
            <input type="text" name='title' value="{{article.title}}" />
        </label>
        <br/>
        <label for="">文章内容
            <input type="text" name='content' value="{{article.content}}" />
        </label>
        <br/>

        <input type="submit" value='发送提交'>
        <br/>

    </form>
</body>

</html>

second_django/myblog/blog/templates/blog/edit_page备份.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit_Page</title>
</head>

<body>
    <form action="{%url 'blog:edit_action'%}" method='post'>
        {%csrf_token%} 
        {%if article %}
            <input type='hidden' name="article_id" value="{{article.id}}"/>
            <label for="">文章标题
                <input type="text" name='title' value="{{article.title}}"/>
            </label>
            <br/>
            <label for="">文章内容
                <input type="text" name='content' value="{{article.content}}"/>
            </label>
            <br/> 
        {%else%}
            <input type='hidden' name="article_id" value="0"/>
            <label for="">文章标题
                <input type="text" name='title'/>
            </label>
            <br/>
            <label for="">文章内容
                <input type="text" name='content'/>
            </label>
            <br/> 
        {%endif%}
        <input type="submit" value='发送提交'>
        <br/>

    </form>
</body>

</html>

second_django/myblog/blog/templates/blog/index.html
<!-- from django.contrib import messages -->

<!-- #向此模板中传入参数 {'articles':articles} -->
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>second_django</title>
</head>
<body>

    <!-- <h1>{{ article.title }}</h1>
    <h3>{{article.content}}</h3> -->
    <h1><a href="{%url 'blog:edit_page' 0%}">新文章</a></h1>
    <!-- <script>alert({{article.id}});</script> -->
    {%for article in articles%}
    <br/>
    <!--  url关键字  应用程序:视图函数  传给视图函数的参数  -->
    <a href="{%url 'blog:article_page' article.id%}">{{article.title}}</a>
    <!-- <a href="{%url 'blog:article_page' article.id%}">{{article.title}}</a> -->
    <br/>
    {%endfor%}
</body>
</html>

second_django/myblog/blog/templates/blog/test.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>test</title>
</head>
<body>
    <h1>test</h1>
</body>
</html>