third_django/myblog/blog/urls.py
from django.urls import path,re_path
from . import views
app_name='blog'
print('blog_urls')
urlpatterns = [    
    re_path(r'^index/', views.index,name='index'),
    # path(  route,       view,        kwargs=None,         name=None)
    # article_id
    re_path(r'^edit/(?:(?P<article_id>\d+)/)?$',views.edit_page,name='edit_page'),
    re_path(r'^article/(?P<article_id>\d+)/detail/$',views.article_detail,name='article_detail'),
    re_path(r'^edit/result/$',views.edit_submit_result,name='edit_submit_result'),
    
]

third_django/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    # path('blog/', include('blog.urls'))
]

third_django/myblog/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=33,default='title')
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(null=True)
    def __str__(self):
        return self.title

third_django/myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .import models
# Create your views here.
def index(request):
    articles=models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})

def edit_page(request,article_id):
    # article_id当前修改的文章ID号
    #根据article_id显示当前显示的标题和内容
    if str(article_id)==str(0):
        #给edit_page.html页面传送article_id为0的article
        article=''
    else:
        article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/edit_page.html',{'article':article})

def article_detail(request,article_id):
    print('进入文章详情页_views_article_detail')  
    article=models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_detail.html',{'article':article})
def edit_submit_result(request):
    result='准备写入数据库'
    try:
        print('进入文章修改结果页_edit_submit_result') 
        article_id=request.POST.get('article_id','article_id')
        title=request.POST.get('title','TITLE')
        content=request.POST.get('content','CONTENT')
        print('从编辑页面传回来的参数title和content以及article_id')
        print(title)
        print(content)
        print(article_id)
        if str(article_id)==str(0):
            models.Article.objects.create(title=title,content=content)
            result='新文章写入数据库成功'
        else:
            article=models.Article.objects.get(pk=article_id)
            article.title=title
            article.content=content
            article.save()
            result='原有文章修改成功'
    except Exception:
        result='写入数据库失败'
    return render(request,'blog/edit_submit_result.html',{'result':result})

third_django/myblog/blog/templates/blog/article_detail.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <h1><a href="{%url 'blog:edit_page' article.id%}">修改此文</a></h1>

    <br/>
    <h5>第{{article.id}}篇文章</h5>
    <br/>
    <br/>
    <h1>标题<br/>{{article.title}}
    </h1>
    <br/>
    <br/>
    <h3>内容<br/>{{article.content}}</h3>
    <br/>

</body>

</html>

third_django/myblog/blog/templates/blog/edit_page.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>新建或修改文章页面</title>
</head>
<body>
    <h1>新建或修改文章页面{{article_id}}</h1>

    <!-- 一个文章标题
    一个文章内容 -->
    <form action="{%url 'blog:edit_submit_result'%}" method='post'>
        {%csrf_token%}       
        <input type='hidden' name='article_id' value="{{article.id | default:'0'}}" />
        <label>文章标题
            <input type="text" name='title' value="{{article.title | default:'title'}}" />
        </label>
        <br/><br/>
        <label>文章内容
            <input type="text" name='content' value="{{article.content | default:'content'}}" />
        </label>
        <br/><br/>
        <input type="submit" value='发送提交' />
    </form>







</body>
</html>

third_django/myblog/blog/templates/blog/edit_submit_result.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <br/>
    <h1>原来的文章 + 新增的文章</h1>
    <br/>
    <br/>
    <h1>编辑结果    {{result}}</h1>
    <br/>
    <h1><a href='{%url 'blog:index'%}' >回到主页</a></h1>
</body>
</html>

third_django/myblog/blog/templates/blog/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <!-- #显示数据库中的数据 -->
    {%for article in articles%}
    <br/>
    <!-- 点击文章标题,进入文章详情页 -->
    <a href="{%url 'blog:article_detail' article.id%}">{{article.id}}  {{article.title}}</a>
    <!-- {{article.id}}
    
    {{article.content}} -->
    <br/>




    {%endfor%}

        <h1>新建文章: 这个只是文字,不是链接</h1>
    
                <!-- url关键字说明这是一个链接 -->
                <!-- blog应用名称 -->
                <!-- edit_page视图函数 -->
                <!-- 必须用单引号引起来 -->
    <!-- 从这个发出去一个链接
    Request URL: http://localhost:8000/blog/edit/ -->
    <h1><a href="{%url 'blog:edit_page' 0%}">新建文章链接</a></h1>
    
</body>
</html>